version: '3'

services:
  app:
    build: .
    image: testassigmenthttpapi-app:latest
    container_name: app
    ports:
      - "8000:8000"
    command: bash -c "echo '*****     To reach API interface please follow this link -- http://localhost:8000/docs'
             && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    volumes:
      - ./database.db:/app/database.db:delegated